package enums;

public enum ResponseType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    INVALID_DATA, 
    ALREADY_LOGGED_IN,
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    USER_EXISTS,
    ONLINE_PLAYERS,
    LEADERBOARD_PLAYERS,
    INVITE_RECEIVED,
    INVITE_ACCEPTED,
    INVITE_REJECTED,
    ERROR
}
