package enums;

public enum ResponseType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    INVALID_DATA, 
    ALREADY_LOGGED_IN,
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    USER_EXISTS,
    ONLINE_PLAYERS,
    LEADERBOARD,
    GAME_INVITE,
    INVITE_ACCEPTED,
    INVITE_REJECTED,
    JOIN_GAME,
    GAME_STARTED,
    GAME_UPDATE,
    GAME_ENDED,
    ERROR,
    REMATCH_REQUESTED
}
